experiment_dir: /Users/thomaseffland/Development/infonet/experiments/
tagger: /Users/thomaseffland/Development/infonet/experiments/tagger_Feb-02-2017-18:24:207917/
# TODO: Allow an 'infer best' option that automatically picks best tagger

train:
  n_epoch: 100
  batch_size: 50
  patience: 20

optimizer:
  type: Adam
  learning_rate: .01
  weight_decay: 0.0
  grad_clip: 10.

extractor:
  use_gold_boundaries: True
  build_on_tagger_features: False
  backprop_to_tagger: False
  shared_options:
    gru_state_sizes: [ 100 ]  # more than one creates stacked grus
    bidirectional: True
    gru_dropouts: [ .5 ]      # dropouts on outputs of gru
    gru_hdropouts: [ .0 ]     # horizontal dropouts on gru (overrides gru_dropouts if > 0)
    mlp_sizes: [  ]            # hidden layer sizes
    mlp_activations: [  ]      # eg, sigmoid or leaky_relu
    mlp_dropouts: [  ]         # dropout for mlp layers
  mention_options:
    gru_state_sizes: [  ]  # more than one creates stacked grus
    bidirectional: True
    gru_dropouts: [ ]      # dropouts on outputs of gru
    gru_hdropouts: [ ]     # horizontal dropouts on gru (overrides gru_dropouts if > 0)
    mlp_sizes: [ 50 ]            # hidden layer sizes
    mlp_activations: [ leaky_relu ]      # eg, sigmoid or leaky_relu
    mlp_dropouts: [ .25 ]         # dropout for mlp layers
    pooling: avg               # choose from [sum, avg, max, logsumexp, attention]
    include_width: True    # include the width of the pooling span as a feature
  relation_options:
    gru_state_sizes: [ ]  # more than one creates stacked grus
    bidirectional: True
    gru_dropouts: [  ]      # dropouts on outputs of gru
    gru_hdropouts: [  ]     # horizontal dropouts on gru (overrides gru_dropouts if > 0)
    mlp_sizes: [ 50 ]            # hidden layer sizes
    mlp_activations: [ leaky_relu ]      # eg, sigmoid or leaky_relu
    mlp_dropouts: [ .25 ]         # dropout for mlp layers
    pooling: avg               # choose from [sum, avg, max, logsumexp, attention]
    outer_window_size: 5      # size of context window outside of mentions when pooling
    include_width: True    # include the inner width of the pooling span as a feature
    max_r_dist: 'infer'    # max token dist between mentions to automatically prune to NULL. 'infer' figures out from data
  classification_options:
    constraint_mask: True   # whether to automatically apply class compatibility masking
    method: staged     # choose from [staged, mean_field, loopy_bp]
